import db from "./pgclient.js";

const folderInput = document.getElementById("folderInput");
const log = document.getElementById("log");

const genQuery = async (db) => {
  return async (cmd) => {
    console.log(cmd);
    await db.query(cmd);
  };
};
const query = await genQuery(db);

document.getElementById("uploadBtn")?.addEventListener("click", async () => {
  const files = folderInput.files;
  if (!files || files.length === 0) {
    log.textContent = "先にフォルダを選択してください。";
    return;
  }

  try {
    await query("BEGIN");

    await db.query(`DROP TABLE IF EXISTS room`);
    await db.query(`DROP TABLE IF EXISTS tmpptn`);
    await db.query(`
      CREATE TEMP TABLE tmpptn (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        settings TEXT NOT NULL,
        partname TEXT,
        UNIQUE (settings)
      ) ON COMMIT DROP;
    `);
    await db.query(`
      CREATE TEMP TABLE room (
        room INTEGER NOT NULL,
        ptn_id INTEGER NOT NULL
      ) ON COMMIT DROP;
    `);

    let ret;
    for (const file of files) {
      const settings = await file.text();
      const room = file.webkitRelativePath.split("/")[1];
      ret = await db.query(
        `
        INSERT INTO tmpptn (settings) VALUES ($1)
        ON CONFLICT (settings) DO UPDATE SET settings = EXCLUDED.settings
        RETURNING id
        `,
        [settings],
      );
      const ptnid = ret.rows[0].id;
      await db.query(
        `
        INSERT INTO room (room, ptn_id) VALUES ($1, $2)
        `,
        [room, ptnid],
      );
    }
    displayModal();
  } catch (err) {
    console.error(err);
    await query("ROLLBACK");
  }
});

async function displayModal() {
  try {
    const ptnRet = await db.query(`SELECT * FROM tmpptn`);
    const roomRet = await db.query(`SELECT * FROM room`);

    console.log("ptnRet:", ptnRet.rows);
    console.log("roomRet:", roomRet.rows);

    const data = await db.query(`
      SELECT t.id, array_to_string(array_agg(r.room ORDER BY r.room::INTEGER), ',') AS rooms
      FROM tmpptn t
      JOIN (
        SELECT room, ptn_id, ROW_NUMBER() OVER (PARTITION BY ptn_id ORDER BY room::INTEGER) AS rn FROM room
      ) r ON t.id = r.ptn_id AND r.rn <= 3
      GROUP BY t.id
      `);
    console.log(data.rows);

    const tbody = document.querySelector("#roomTable tbody");
    tbody.innerHTML = data.rows
      .map(
        (row) => `
      <tr data-ptnid="${row.id}">
        <td style="border: 1px solid #ccc; padding: 8px;">${row.rooms}等</td>
        <td style="border: 1px solid #ccc; padding: 8px;">
          <select>
            <option value="partA">partA</option>
            <option value="partB">partB</option>
            <option value="partC">partC</option>
          </select>
        </td>
      </tr>
    `,
      )
      .join("");

    document.querySelector("#partSelector").showModal();
  } catch (err) {
    console.error(err);
    await query("ROLLBACK");
    document.querySelector("#partSelector").close();
  }
}

document.getElementById("closeBtn")?.addEventListener("click", async () => {
  await query("COMMIT");
  document.querySelector("#partSelector").close();
});

document.getElementById("saveBtn")?.addEventListener("click", async () => {
  try {
    const rows = document.querySelectorAll("#roomTable tbody tr");
    for (const row of rows) {
      const ptnId = row.getAttribute("data-ptnid");
      const select = row.querySelector("select");
      const partName = select.value;

      await db.query(
        `
      UPDATE tmpptn
      SET partname = $1
      WHERE id = $2
      `,
        [partName, ptnId],
      );
    }

    const ret = await db.query(`SELECT * FROM tmpptn`);
    console.log(ret.rows);

    await query("COMMIT");
  } catch (err) {
    console.error(err);
    await query("ROLLBACK");
  } finally {
    document.querySelector("#partSelector").close();
  }
});
