import db from "./pgclient.js";
import env from "./nunjucks.js";

const folderInput = document.getElementById("folderInput");
const log = document.getElementById("log");

const genQuery = async () => {
  return async (cmd) => {
    console.log(cmd);
    await db.query(cmd);
  };
};
const query = await genQuery();

document.getElementById("uploadBtn")?.addEventListener("click", async () => {
  const files = folderInput.files;
  if (!files || files.length === 0) {
    log.textContent = "先にフォルダを選択してください。";
    return;
  }

  try {
    await query("BEGIN");

    await db.query(`DROP TABLE IF EXISTS room`);
    await db.query(`DROP TABLE IF EXISTS tmpptn`);
    await db.query(`
      CREATE TEMP TABLE tmpptn (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        settings TEXT NOT NULL,
        partname TEXT,
        UNIQUE (settings)
      ) ON COMMIT DROP;
    `);
    await db.query(`
      CREATE TEMP TABLE tmproom (
        name INTEGER NOT NULL,
        ptn_id INTEGER NOT NULL
      ) ON COMMIT DROP;
    `);

    let ret;
    for (const file of files) {
      const settings = await file.text();
      const roomname = file.webkitRelativePath.split("/")[1];
      ret = await db.query(
        `
        INSERT INTO tmpptn (settings) VALUES ($1)
        ON CONFLICT (settings) DO UPDATE SET settings = EXCLUDED.settings
        RETURNING id
        `,
        [settings],
      );
      const ptnid = ret.rows[0].id;
      await db.query(
        `
        INSERT INTO tmproom (name, ptn_id) VALUES ($1, $2)
        `,
        [roomname, ptnid],
      );
    }
    await genDispModal()();
  } catch (err) {
    console.error(err);
    await query("ROLLBACK");
  }
});

const genDispModal = () => {
  return async () => {
    try {
      const ptnRet = await db.query(`SELECT * FROM tmpptn`);
      const roomRet = await db.query(`SELECT * FROM tmproom`);

      const data = await db.query(`
      SELECT t.id, array_to_string(array_agg(r.name ORDER BY r.name::INTEGER), ',') AS rooms
      FROM tmpptn t
      JOIN (
        SELECT name, ptn_id, ROW_NUMBER() OVER (PARTITION BY ptn_id ORDER BY name::INTEGER) AS rn FROM tmproom
      ) r ON t.id = r.ptn_id AND r.rn <= 3
      GROUP BY t.id
      `);

      const renderedHtml = env.render("partSelector.html", { rows: data.rows });
      const dialog = document.querySelector("#partSelector");
      if (dialog) {
        dialog.innerHTML = renderedHtml;
      } else {
        throw new Error("Dialog element not found");
      }

      document
        .getElementById("closeBtn")
        ?.addEventListener("click", closeModal);
      document
        .getElementById("saveBtn")
        ?.addEventListener("click", savePartNames);

      document.querySelector("#partSelector").showModal();
    } catch (err) {
      console.error(err);
      await query("ROLLBACK");
      document.querySelector("#partSelector").close();
    }
  };
};

const genClose = () => {
  return async () => {
    await query("COMMIT");
    document.querySelector("#partSelector").close();
  };
};
const genSavePartNames = () => {
  return async () => {
    try {
      const rows = document.querySelectorAll("#roomTable tbody tr");
      for (const row of rows) {
        const ptnId = row.getAttribute("data-ptnid");
        const select = row.querySelector("select");
        const partName = select.value;

        await db.query(
          `
      UPDATE tmpptn
      SET partname = $1
      WHERE id = $2
      `,
          [partName, ptnId],
        );
      }

      const res = await fetch("/upload", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          ptn: await db.query(`SELECT * FROM tmpptn`),
          room: await db.query(`SELECT * FROM tmproom`),
        }),
      });
      if (!res.ok) throw new Error("Upload failed");
      const text = await res.text();
      console.log(text);

      await query("COMMIT");
    } catch (err) {
      console.error(err);
      await query("ROLLBACK");
    } finally {
      document.querySelector("#partSelector").close();
    }
  };
};
const closeModal = genClose();
const savePartNames = genSavePartNames();
