import pool from "./client.js";
import express from "express";
import path from "path";
import multer from "multer";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const upload = multer({ storage: multer.memoryStorage(), preservePath: true });

const app = express();
const PORT = 52000;

app.get("/", async (req, res) => {
  console.log("GET /");
  res.sendFile(path.join(__dirname, "index.html"));
});

app.get("/debug", async (req, res) => {
  console.log("GET /debug");
  const client = await pool.connect();
  try {
    const ret = await client.query("SELECT * FROM public.building");
    res.send(ret.rows);
  } catch (err) {
    console.error(err);
    res.status(500).send("Internal Server Error");
  } finally {
    await client.release();
  }
});

app.post("/upload-folder", upload.array("files"), async (req, res) => {
  // 入力チェック
  const files = req.files || [];
  if (files.length === 0) return res.status(400).send("No files uploaded");
  const buildingid = Number(req.body.buildingid);
  if (isNaN(buildingid) || buildingid <= 0)
    return res.status(400).send("No building ID provided");

  const client = await pool.connect();
  try {
    await client.query("BEGIN");

    // 古いデータを削除
    await client.query(
      `
      DELETE FROM public.setptn p
      WHERE p.id IN (
        SELECT DISTINCT r.ptnid
        FROM public.room r
        WHERE r.buildingid = $1
    );`,
      [buildingid],
    );
    await client.query(`DELETE FROM public.room WHERE buildingid = $1`, [
      buildingid,
    ]);

    // シーケンスの現在値を取得
    let ret = await client.query(
      `SELECT nextval(pg_get_serial_sequence('public.setptn','id')) as nextval`,
    );
    let currid = ret.rows[0].nextval;

    // 一時テーブル作成
    await client.query(`
      CREATE TEMP TABLE tmpset (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        settings JSONB NOT NULL,
        UNIQUE (settings)
      ) ON COMMIT DROP;
    `);
    // シーケンスの値を設定
    await client.query(
      `SELECT setval(pg_get_serial_sequence('tmpset','id'),$1,true)`,
      [Number(currid)],
    );

    for (const file of files) {
      const roomnum = file.originalname.split("/")[1];

      const lines = file.buffer
        .toString("utf-8")
        .trim()
        .split(/\r?\n/)
        .map((s) => s.trim())
        .filter((s) => s.length > 0);

      const headers = ["main", "sub1", "sub2", "val"];
      const records = lines.map((line) => {
        const cols = line.split(",").map((c) => c.trim());
        return Object.fromEntries(
          headers.map((h, i) => [h, Number(cols[i]) ?? null]),
        );
      });
      // 設定パターンの重複を確認
      ret = await client.query(
        `
      WITH ins AS (
        INSERT INTO tmpset (settings)
        VALUES ($1::jsonb)
        ON CONFLICT (settings) DO NOTHING
        RETURNING id
      )
      SELECT id FROM ins
      UNION ALL
      SELECT t.id
      FROM tmpset t
      WHERE t.settings = $1::jsonb
      LIMIT 1`,
        [JSON.stringify(records)],
      );
      const id = ret.rows[0].id;
      if (currid != id) {
        // 重複なしの場合

        // パターンテーブルにインサート
        await client.query(`INSERT INTO public.setptn (name) VALUES ($1)`, [
          `ptn_${id}`,
        ]);
        const ret = await client.query(`SELECT * FROM public.setptn`);

        // 設定テーブルにインサート
        const rowsForInsert = records.map((r) => ({
          ...r,
          ptnid: id,
        }));
        await client.query(
          `
          INSERT INTO public.setting (main, sub1, sub2, val, ptnid)
          SELECT x.main, x.sub1, x.sub2, x.val, x.ptnid
          FROM jsonb_to_recordset($1::jsonb) AS x(main int, sub1 int, sub2 int, val int, ptnid int)
        `,
          [JSON.stringify(rowsForInsert)],
        );
      }
      // roomテーブルにインサート
      await client.query(
        `INSERT INTO public.room (name, buildingid, ptnid) VALUES ($1, $2, $3)`,
        [roomnum, buildingid, id],
      );
      currid = id;
    }

    console.log("COMMIT");
    await client.query("COMMIT");
    return res.status(200).send("uploaded " + files.length + " files");
  } catch (err) {
    console.error(err);
    console.log("ROLLBACK");
    await client.query("ROLLBACK");
    return res.status(500).send("Internal Server Error");
  } finally {
    console.log("RELEASE");
    await client.release();
  }
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Example app listening on PORT ${PORT}`);
});
